//Work in progress...


// import { expect } from "@wdio/globals";
// import MainPage from "../pageobjects/main.page.ts";

// describe("Rentzila", () => {
 
//   it('C200- Authorization with empty fields', async () => {
//     await MainPage.open();

//     await MainPage.clickOnLoginButton()
//     await expect(MainPage.authorizationFormTitle).toBeExisting()
//     await expect(MainPage.authorizationFormTitle).toHaveText("Вхід")
//     await MainPage.clickOnEnterButton()
//     await expect(MainPage.emailOrPhoneNumberFieldErrorMessage).toBeExisting()
//     await expect(MainPage.emailOrPhoneNumberFieldErrorMessage).toHaveText("Поле не може бути порожнім")
//     await expect(MainPage.passwordFieldErrorMessage).toBeExisting()
//     await expect(MainPage.passwordFieldErrorMessage).toHaveText("Поле не може бути порожнім")
//     await MainPage.enterEmailInEmailOrPhoneNumberField("nastya.zkhrvvvv@gmail.com")
//     await MainPage.clickOnEnterButton()
//     await expect(MainPage.passwordFieldErrorMessage).toBeExisting()
//     await expect(MainPage.passwordFieldErrorMessage).toHaveText("Поле не може бути порожнім")
//     await MainPage.clickOnAuthorizationCrossButton()
//     await MainPage.clickOnLoginButton()
//     await expect(MainPage.authorizationFormTitle).toBeExisting()
//     await expect(MainPage.authorizationFormTitle).toHaveText("Вхід")
//     await MainPage.enterPasswordInPasswordField("4CfzPLpFyzFM82Z")
//     await MainPage.clickOnEnterButton()
//     await expect(MainPage.emailOrPhoneNumberFieldErrorMessage).toBeExisting()
//     await expect(MainPage.emailOrPhoneNumberFieldErrorMessage).toHaveText("Поле не може бути порожнім")

//   });
//   it('C201-  Authorization with valid email and password', async () => {
//     await MainPage.open();

//     await MainPage.clickOnLoginButton()
//     await expect(MainPage.authorizationFormTitle).toBeExisting()
//     await expect(MainPage.authorizationFormTitle).toHaveText("Вхід")
//     await MainPage.enterEmailInEmailOrPhoneNumberField("nastya.zkhrvvvv@gmail.com")
//     await MainPage.enterPasswordInPasswordField("4CfzPLpFyzFM82Z")
//     await MainPage.clickOnHiddenPasswordButton()
//     await MainPage.clickOnHiddenPasswordButton()
//     await MainPage.clickOnEnterButton()
//     //todo:complete test
   

//   });
//   it('C202-  Authorization with valid phone and password', async () => {
//     await MainPage.open();

//     await MainPage.clickOnLoginButton()
//     await expect(MainPage.authorizationFormTitle).toBeExisting()
//     await expect(MainPage.authorizationFormTitle).toHaveText("Вхід")
//     await MainPage.enterEmailInEmailOrPhoneNumberField("+380991234784")
//     await MainPage.enterPasswordInPasswordField("4CfzPLpFyzFM82Z")
//     await MainPage.clickOnEnterButton()
//     await MainPage.clickOnUserIconDropdown()
//     await expect(MainPage.myProfileItem).toBeExisting()
//     await expect(MainPage.myProfileItem).toHaveText("Мій профіль")
//     await MainPage.clickOnMyProfile()
//     await expect(MainPage.myProfileTitle).toBeExisting()
//     await expect(MainPage.myProfileTitle).toHaveText("Мій профіль")
//     // add check entered phone number previously should be displayed and verified in the ""Номер телефону"" Input.
//     await MainPage.clickOnUserIconDropdown()
//     await expect(MainPage.myProfileItem).toBeExisting()
//     await expect(MainPage.myProfileItem).toHaveText("Мій профіль")
//     await MainPage.clickOnLogoutButton()
//     await expect(MainPage.logo).toBeExisting()
//     await MainPage.clickOnLoginButton()
//     await expect(MainPage.authorizationFormTitle).toBeExisting()
//     await expect(MainPage.authorizationFormTitle).toHaveText("Вхід")
//     await MainPage.enterEmailInEmailOrPhoneNumberField("380991234784")
//     await MainPage.enterPasswordInPasswordField("4CfzPLpFyzFM82Z")
//     await MainPage.clickOnEnterButton()
//     await MainPage.clickOnUserIconDropdown()
//     await expect(MainPage.myProfileItem).toBeExisting()
//     await expect(MainPage.myProfileItem).toHaveText("Мій профіль")
//     await MainPage.clickOnLogoutButton()
//     await expect(MainPage.logo).toBeExisting()
//     await MainPage.clickOnLoginButton()
//     await expect(MainPage.authorizationFormTitle).toBeExisting()
//     await expect(MainPage.authorizationFormTitle).toHaveText("Вхід")
//     await MainPage.enterEmailInEmailOrPhoneNumberField("0991234784")
//     await MainPage.enterPasswordInPasswordField("4CfzPLpFyzFM82Z")
//     await MainPage.clickOnEnterButton()

//   });
//   it('C207-  Authorization with invalid phone', async () => {
//     await MainPage.open();

//     await MainPage.clickOnLoginButton()
//     await expect(MainPage.authorizationFormTitle).toBeExisting()
//     await expect(MainPage.authorizationFormTitle).toHaveText("Вхід")
//     await MainPage.enterEmailInEmailOrPhoneNumberField("991234784")
//     await MainPage.enterPasswordInPasswordField("4CfzPLpFyzFM82Z")
//     await MainPage.clickOnEnterButton()
//     await expect(MainPage.emailOrPhoneNumberFieldErrorMessage).toBeExisting()
//     await expect(MainPage.emailOrPhoneNumberFieldErrorMessage).toHaveText("Неправильний формат email або номера телефону")
//     await MainPage.clickOnAuthorizationCrossButton()
//     await MainPage.clickOnLoginButton()
//     await expect(MainPage.authorizationFormTitle).toBeExisting()
//     await expect(MainPage.authorizationFormTitle).toHaveText("Вхід")
//     await MainPage.enterEmailInEmailOrPhoneNumberField("099123478")
//     await MainPage.enterPasswordInPasswordField("4CfzPLpFyzFM82Z")
//     await MainPage.clickOnEnterButton()
//     await expect(MainPage.emailOrPhoneNumberFieldErrorMessage).toBeExisting()
//     await expect(MainPage.emailOrPhoneNumberFieldErrorMessage).toHaveText("Неправильний формат email або номера телефону")
//     await MainPage.clickOnAuthorizationCrossButton()
//     await MainPage.clickOnLoginButton()
//     await expect(MainPage.authorizationFormTitle).toBeExisting()
//     await expect(MainPage.authorizationFormTitle).toHaveText("Вхід")
//     await MainPage.enterEmailInEmailOrPhoneNumberField("+380-99-123-4784")
//     await MainPage.enterPasswordInPasswordField("4CfzPLpFyzFM82Z")
//     await MainPage.clickOnEnterButton()
//     await expect(MainPage.emailOrPhoneNumberFieldErrorMessage).toBeExisting()
//     await expect(MainPage.emailOrPhoneNumberFieldErrorMessage).toHaveText("Неправильний формат email або номера телефону")
//     await MainPage.clickOnAuthorizationCrossButton()
//     await MainPage.clickOnLoginButton()
//     await expect(MainPage.authorizationFormTitle).toBeExisting()
//     await expect(MainPage.authorizationFormTitle).toHaveText("Вхід")
//     await MainPage.enterEmailInEmailOrPhoneNumberField("+380_99_123_4784")
//     await MainPage.enterPasswordInPasswordField("4CfzPLpFyzFM82Z")
//     await MainPage.clickOnEnterButton()
//     await expect(MainPage.emailOrPhoneNumberFieldErrorMessage).toBeExisting()
//     await expect(MainPage.emailOrPhoneNumberFieldErrorMessage).toHaveText("Неправильний формат email або номера телефону")
//     await MainPage.clickOnAuthorizationCrossButton()
//     await MainPage.clickOnLoginButton()
//     await expect(MainPage.authorizationFormTitle).toBeExisting()
//     await expect(MainPage.authorizationFormTitle).toHaveText("Вхід")
//     await MainPage.enterEmailInEmailOrPhoneNumberField("+380(99)1234784")
//     await MainPage.enterPasswordInPasswordField("4CfzPLpFyzFM82Z")
//     await MainPage.clickOnEnterButton()
//     await expect(MainPage.emailOrPhoneNumberFieldErrorMessage).toBeExisting()
//     await expect(MainPage.emailOrPhoneNumberFieldErrorMessage).toHaveText("Неправильний формат email або номера телефону")
//     await MainPage.clickOnAuthorizationCrossButton()
//     await MainPage.clickOnLoginButton()
//     await expect(MainPage.authorizationFormTitle).toBeExisting()
//     await expect(MainPage.authorizationFormTitle).toHaveText("Вхід")
//     await MainPage.enterEmailInEmailOrPhoneNumberField("(99)1234784")
//     await MainPage.enterPasswordInPasswordField("4CfzPLpFyzFM82Z")
//     await MainPage.clickOnEnterButton()
//     await expect(MainPage.emailOrPhoneNumberFieldErrorMessage).toBeExisting()
//     await expect(MainPage.emailOrPhoneNumberFieldErrorMessage).toHaveText("Неправильний формат email або номера телефону")
//     await MainPage.clickOnAuthorizationCrossButton()
//     await MainPage.clickOnLoginButton()
//     await expect(MainPage.authorizationFormTitle).toBeExisting()
//     await expect(MainPage.authorizationFormTitle).toHaveText("Вхід")
//     await MainPage.enterEmailInEmailOrPhoneNumberField("09912347840")
//     await MainPage.enterPasswordInPasswordField("4CfzPLpFyzFM82Z")
//     await MainPage.clickOnEnterButton()
//     await expect(MainPage.emailOrPhoneNumberFieldErrorMessage).toBeExisting()
//     await expect(MainPage.emailOrPhoneNumberFieldErrorMessage).toHaveText("Неправильний формат email або номера телефону")
//     await MainPage.clickOnAuthorizationCrossButton()
//     await MainPage.clickOnLoginButton()
//     await expect(MainPage.authorizationFormTitle).toBeExisting()
//     await expect(MainPage.authorizationFormTitle).toHaveText("Вхід")
//     await MainPage.enterEmailInEmailOrPhoneNumberField("+480991234784")
//     await MainPage.enterPasswordInPasswordField("4CfzPLpFyzFM82Z")
//     await MainPage.clickOnEnterButton()
//     await expect(MainPage.emailOrPhoneNumberFieldErrorMessage).toBeExisting()
//     await expect(MainPage.emailOrPhoneNumberFieldErrorMessage).toHaveText("Неправильний формат email або номера телефону")
//     await MainPage.clickOnAuthorizationCrossButton()
//     await MainPage.clickOnLoginButton()
//     await expect(MainPage.authorizationFormTitle).toBeExisting()
//     await expect(MainPage.authorizationFormTitle).toHaveText("Вхід")
//     await MainPage.enterEmailInEmailOrPhoneNumberField("+991234784")
//     await MainPage.enterPasswordInPasswordField("4CfzPLpFyzFM82Z")
//     await MainPage.clickOnEnterButton()
//     await expect(MainPage.emailOrPhoneNumberFieldErrorMessage).toBeExisting()
//     await expect(MainPage.emailOrPhoneNumberFieldErrorMessage).toHaveText("Неправильний формат email або номера телефону")
//     await MainPage.clickOnAuthorizationCrossButton()
//     await MainPage.clickOnLoginButton()
    
//   });

//  it('576-  Authorization with invalid email', async () => {
//     await MainPage.open();
    
//     await MainPage.clickOnLoginButton()
//     await expect(MainPage.authorizationFormTitle).toBeExisting()
//     await expect(MainPage.authorizationFormTitle).toHaveText("Вхід")
//     await MainPage.enterEmailInEmailOrPhoneNumberField("nastya___zkhrvvvv@gmail.com")
//     await MainPage.enterPasswordInPasswordField("4CfzPLpFyzFM82Z")
//     await MainPage.clickOnEnterButton()
//     await expect(MainPage.incorrectEmailOrPasswordErrorMessage).toBeExisting()
//     await expect(MainPage.incorrectEmailOrPasswordErrorMessage).toHaveText("Невірний e-mail або пароль")
//     await MainPage.clickOnAuthorizationCrossButton()
//     await MainPage.clickOnLoginButton()
//     await expect(MainPage.authorizationFormTitle).toBeExisting()
//     await expect(MainPage.authorizationFormTitle).toHaveText("Вхід")
//     await MainPage.enterEmailInEmailOrPhoneNumberField("еуіегіуккутеяшдф@gmail.com")
//     await MainPage.enterPasswordInPasswordField("4CfzPLpFyzFM82Z")
//     await MainPage.clickOnEnterButton()
//     await expect(MainPage.emailOrPhoneNumberFieldErrorMessage).toBeExisting()
//     await expect(MainPage.emailOrPhoneNumberFieldErrorMessage).toHaveText("Неправильний формат email або номера телефону")
//     await MainPage.clickOnAuthorizationCrossButton()
//     await MainPage.clickOnLoginButton()
//     await expect(MainPage.authorizationFormTitle).toBeExisting()
//     await expect(MainPage.authorizationFormTitle).toHaveText("Вхід")
//     await MainPage.enterEmailInEmailOrPhoneNumberField("nastya.zkhrvvvvgmail.com")
//     await MainPage.enterPasswordInPasswordField("4CfzPLpFyzFM82Z")
//     await MainPage.clickOnEnterButton()
//     await expect(MainPage.emailOrPhoneNumberFieldErrorMessage).toBeExisting()
//     await expect(MainPage.emailOrPhoneNumberFieldErrorMessage).toHaveText("Неправильний формат email або номера телефону")
//     await MainPage.clickOnAuthorizationCrossButton()
//     await MainPage.clickOnLoginButton()
//     await expect(MainPage.authorizationFormTitle).toBeExisting()
//     await expect(MainPage.authorizationFormTitle).toHaveText("Вхід")
//     await MainPage.enterEmailInEmailOrPhoneNumberField("nastya.zkhrvvvv@gmailcom")
//     await MainPage.enterPasswordInPasswordField("4CfzPLpFyzFM82Z")
//     await MainPage.clickOnEnterButton()
//     await expect(MainPage.emailOrPhoneNumberFieldErrorMessage).toBeExisting()
//     await expect(MainPage.emailOrPhoneNumberFieldErrorMessage).toHaveText("Неправильний формат email або номера телефону")
//     await MainPage.clickOnAuthorizationCrossButton()
//     await MainPage.clickOnLoginButton()
//     await expect(MainPage.authorizationFormTitle).toBeExisting()
//     await expect(MainPage.authorizationFormTitle).toHaveText("Вхід")
//     await MainPage.enterEmailInEmailOrPhoneNumberField("nastya.zkhrvvvv@gmail")
//     await MainPage.enterPasswordInPasswordField("4CfzPLpFyzFM82Z")
//     await MainPage.clickOnEnterButton()
//     await expect(MainPage.emailOrPhoneNumberFieldErrorMessage).toBeExisting()
//     await expect(MainPage.emailOrPhoneNumberFieldErrorMessage).toHaveText("Неправильний формат email або номера телефону")
//     await MainPage.clickOnAuthorizationCrossButton()
//     await MainPage.clickOnLoginButton()
//     await expect(MainPage.authorizationFormTitle).toBeExisting()
//     await expect(MainPage.authorizationFormTitle).toHaveText("Вхід")
//     await MainPage.enterEmailInEmailOrPhoneNumberField("nastya.zkhrvvvv.com")
//     await MainPage.enterPasswordInPasswordField("4CfzPLpFyzFM82Z")
//     await MainPage.clickOnEnterButton()
//     await expect(MainPage.emailOrPhoneNumberFieldErrorMessage).toBeExisting()
//     await expect(MainPage.emailOrPhoneNumberFieldErrorMessage).toHaveText("Неправильний формат email або номера телефону")
//     await MainPage.clickOnAuthorizationCrossButton()
//     await MainPage.clickOnLoginButton()
//     await expect(MainPage.authorizationFormTitle).toBeExisting()
//     await expect(MainPage.authorizationFormTitle).toHaveText("Вхід")
//     await MainPage.enterEmailInEmailOrPhoneNumberField("nastya.zkhrvvvv")
//     await MainPage.enterPasswordInPasswordField("4CfzPLpFyzFM82Z")
//     await MainPage.clickOnEnterButton()
//     await expect(MainPage.emailOrPhoneNumberFieldErrorMessage).toBeExisting()
//     await expect(MainPage.emailOrPhoneNumberFieldErrorMessage).toHaveText("Неправильний формат email або номера телефону")
//     await MainPage.clickOnAuthorizationCrossButton()
//     await MainPage.clickOnLoginButton()
//     await expect(MainPage.authorizationFormTitle).toBeExisting()
//     await expect(MainPage.authorizationFormTitle).toHaveText("Вхід")
//     await MainPage.enterEmailInEmailOrPhoneNumberField("nastya.zkhrvvvv@@gmail.com")
//     await MainPage.enterPasswordInPasswordField("4CfzPLpFyzFM82Z")
//     await MainPage.clickOnEnterButton()
//     await expect(MainPage.emailOrPhoneNumberFieldErrorMessage).toBeExisting()
//     await expect(MainPage.emailOrPhoneNumberFieldErrorMessage).toHaveText("Неправильний формат email або номера телефону")
//     await MainPage.clickOnAuthorizationCrossButton()
//     await MainPage.clickOnLoginButton()

// });

// it('577-  Authorization with invalid password', async () => {
//   await MainPage.open();
  
//   await MainPage.clickOnLoginButton()
//   await expect(MainPage.authorizationFormTitle).toBeExisting()
//   await expect(MainPage.authorizationFormTitle).toHaveText("Вхід")
//   await MainPage.enterEmailInEmailOrPhoneNumberField("nastya.zkhrvvvv@gmail.com")
//   await MainPage.enterPasswordInPasswordField("4CfzPLpFyzFM82Z___")
//   await MainPage.clickOnEnterButton()
//   await expect(MainPage.incorrectEmailOrPasswordErrorMessage).toBeExisting()
//   await expect(MainPage.incorrectEmailOrPasswordErrorMessage).toHaveText("Невірний e-mail або пароль")
//   await MainPage.clickOnAuthorizationCrossButton()
//   await MainPage.clickOnLoginButton()
//   await expect(MainPage.authorizationFormTitle).toBeExisting()
//   await expect(MainPage.authorizationFormTitle).toHaveText("Вхід")
//   await MainPage.enterEmailInEmailOrPhoneNumberField("nastya.zkhrvvvv@gmail.com")
//   await MainPage.enterPasswordInPasswordField("___4CfzPLpFyzFM82Z")
//   await MainPage.clickOnEnterButton()
//   await expect(MainPage.incorrectEmailOrPasswordErrorMessage).toBeExisting()
//   await expect(MainPage.incorrectEmailOrPasswordErrorMessage).toHaveText("Невірний e-mail або пароль")
//   await MainPage.clickOnAuthorizationCrossButton()
//   await MainPage.clickOnLoginButton()
//   await expect(MainPage.authorizationFormTitle).toBeExisting()
//   await expect(MainPage.authorizationFormTitle).toHaveText("Вхід")
//   await MainPage.enterEmailInEmailOrPhoneNumberField("nastya.zkhrvvvv@gmail.com")
//   await MainPage.enterPasswordInPasswordField("4CfzPLpFyzFM82J")
//   await MainPage.clickOnEnterButton()
//   await expect(MainPage.incorrectEmailOrPasswordErrorMessage).toBeExisting()
//   await expect(MainPage.incorrectEmailOrPasswordErrorMessage).toHaveText("Невірний e-mail або пароль")
//   await MainPage.clickOnAuthorizationCrossButton()
//   await MainPage.clickOnLoginButton()
//   await expect(MainPage.authorizationFormTitle).toBeExisting()
//   await expect(MainPage.authorizationFormTitle).toHaveText("Вхід")
//   await MainPage.enterEmailInEmailOrPhoneNumberField("nastya.zkhrvvvv@gmail.com")
//   await MainPage.enterPasswordInPasswordField("4cfzpLpfyzfm82z")
//   await MainPage.clickOnEnterButton()
//   await expect(MainPage.incorrectEmailOrPasswordErrorMessage).toBeExisting()
//   await expect(MainPage.incorrectEmailOrPasswordErrorMessage).toHaveText("Невірний e-mail або пароль")
//   await MainPage.clickOnAuthorizationCrossButton()
//   await MainPage.clickOnLoginButton()
//   await expect(MainPage.authorizationFormTitle).toBeExisting()
//   await expect(MainPage.authorizationFormTitle).toHaveText("Вхід")
//   await MainPage.enterEmailInEmailOrPhoneNumberField("nastya.zkhrvvvv@gmail.com")
//   await MainPage.enterPasswordInPasswordField("4CfZPLPFYZFM82Z")
//   await MainPage.clickOnEnterButton()
//   await expect(MainPage.incorrectEmailOrPasswordErrorMessage).toBeExisting()
//   await expect(MainPage.incorrectEmailOrPasswordErrorMessage).toHaveText("Невірний e-mail або пароль")
  

// });
// });

